Django-Tienda-Virtual--master/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

Django-Tienda-Virtual--master/products/urls.py
from django.urls import path

from . import views

#con esto decimos que todas estas rutas son de la aplicacion products y asi nos evitamos en conflicto
#entre rutas, podemos tener dos o mas rutas con el mismo nombre
app_name = 'products'


urlpatterns = [
    path('search',views.ProductSearchListView.as_view() , name="search"),
    path('<slug:slug>',views.ProductDetailView.as_view() , name="product"),

]

Django-Tienda-Virtual--master/tiendovirtual/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path('usuarios/login', views.login_view, name="login"),
    path('usuarios/logout', views.logout_view, name="logout"),
    path('usuarios/registro', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
      path('orden/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Tienda-Virtual--master/products/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=50)
    description =models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0) #12121.58
    slug = models.SlugField(null=False, blank=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='products/', null=False, blank=False)

    def __str__(self):
        return self.title

#    def save(self, *args, **kwargs):
#        self.slug = slugify(self.title)
#        super(Product, self).save(*args, **kwargs) 


    
def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)
        while Product.objects.filter(slug=slug).exists():
            slug = slugify("{}-{}".format(instance.title,str(uuid.uuid4())[:8]))
            print("Este es slug", slug)

        instance.slug = slug
#antes que un objeto Product se almacene, se ejecutara el callback set_slug
pre_save.connect(set_slug, sender=Product)

Django-Tienda-Virtual--master/products/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Product
from django.views.generic.detail import DetailView
#la clase q permite una consulta con diferentes filtros
from django.db.models import Q

class ProductListView(ListView):
    template_name = 'index.html'
    #consulta
    queryset = Product.objects.all().order_by('-id')

    #pasar el contexto de la clase al template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de Productos'
        print(context)
        context['products'] = context['product_list'] 
        return context

#obtener el detalle de un producto
class ProductDetailView(DetailView):  #id va a ser de la pk
    model = Product
    template_name = 'products/product.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #print(context)
        return context

class ProductSearchListView(ListView):
    template_name = 'products/search.html'
    #consulta
    #queryset = Product.objects.all().order_by('-id')

    #pasar el contexto de la clase al template
    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        #SELCT * FROM products WHERE title like %valor%
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()
        print('Este es query', context['query'])
        return context

Django-Tienda-Virtual--master/products/templates/products/snippets/carousel.html
{% load static %}
       
       
    <div id="carouselExampleIndicators" class="carousel slide my-4 col" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid "  src="{% static 'images/caja.jpg' %}" style="   height: 100%;  width: auto;" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

Django-Tienda-Virtual--master/products/templates/products/snippets/categories.html
      <div class="col-lg-2">

        <h3 class="my-4">Categorías</h3>
    <div class="nav flex-column nav-pills list-group" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="false">Home</a>
      <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Profile</a>
      <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
      <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</a>
    </div>

      </div>

Django-Tienda-Virtual--master/products/templates/products/snippets/list.html
<div class="row">
    <!--Como hay codigo duplicado se genera un nuevo snippet con el for -->
    {% for object in product_list %}
    <div class="col-3 mt-5">
         {% include 'products/snippets/product.html' with product=object %}

    </div>

     {% endfor %}
    </div>

Django-Tienda-Virtual--master/products/templates/products/snippets/product.html
{% load static %}

          <!-- Producto en tarjetas-->
          <div class="card text-center h-100">
            {% if product.image %}
            <img class="card-img-top" src="{{ product.image.url}}" alt="Card image cap" style=" height: 150px; object-fit: cover;">
            {% else %}
            <img class="card-img-top" src="{% static 'images/aimagenot.png' %}" alt="Card image cap" style=" height: 150px; object-fit: cover;">

            {% endif %}
            <div class="card-body">
              <h4 class="card-title">{{product.title}}</h4>
              <p class="card-text"> {{product.description }}</p>
              
            </div>
            <div class="card-footer"> 

            <div class="btn-group">
                <a href="{% url 'products:product' product.slug %}" class="btn btn-outline-success btn-sm"> 
                    👀 ver
                      </a> 

                  <a href="{% url 'products:product' product.slug %}" class="btn btn-outline-danger btn-sm "> 
                     👍🏻
                     <h7> like</h7>
            </a> 

                            <a href="{% url 'products:product' product.slug %}" class="btn btn-outline-warning btn-sm "
                       > 
                     🛒cart
            </a> 
            </div>
                  


            </div> 
          </div>

Django-Tienda-Virtual--master/products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
<div class="input-group">
<input type="text" name="q" value="{{query}}" class="form-control" placeholder="Buscar producto">
<div class="input-group-append">
    <input type="submit" name="" value="Buscar" class="btn btn-success">
</div>

</div>


</form>