Django-Tienda-Virtual--master/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

Django-Tienda-Virtual--master/tiendovirtual/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path('usuarios/login', views.login_view, name="login"),
    path('usuarios/logout', views.logout_view, name="logout"),
    path('usuarios/registro', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
      path('orden/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Tienda-Virtual--master/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        {% include 'messages.html' %}
        
        {% block breadcrumb %}

        {% endblock %}
        <div class="row">

            {% block content %}

            {% endblock %}


        </div>
    </div>
    
</body>

<script src="https://kit.fontawesome.com/a3f0b9d203.js" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

Django-Tienda-Virtual--master/templates/index.html
{% extends 'base.html'%}

{% block content %}

   
       {% include 'products/snippets/categories.html' %}




         <div class="col-10">
            <h1>{{title}}</h1>
        <ul class="list-group">
            <br>
       <h4 class="text-center"> {{message}} </h4>

     <!--   {% include 'products/snippets/carousel.html' %}-->

       {% include 'products/snippets/search.html' %}

       {% include 'products/snippets/list.html' %}


        </ul>


    </div>

{% endblock %}



{% load static %}

Django-Tienda-Virtual--master/templates/messages.html
    {%if messages %}
    {%for message in messages %}
    {% if message.tags == 'success' %}
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">X</button>
<br>
        {{message}}
    </div>
    {% else %}
    <div class="alert alert-danger">
        {{message}}
    </div>
   {% endif %}
    {% endfor %}
    {% endif %}

    <div class="row">

        {% block content %}

        {% endblock %}


    </div>

Django-Tienda-Virtual--master/templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <a class="navbar-brand" href="{% url 'index'  %}">🏪 Ale Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">

    {% if user.is_authenticated %}
        <a class="nav-item nav-link {% if request.path == logout %}active{% endif %}"" href="{{ logout }}">
            <span class="fas fa-sign-out-alt"></span>
            Logout
  
        </a>

        <a class="nav-item nav-link {% if request.path == cart %}active{% endif %}" href="{{ cart }}">
          <span class="fas fa-cart-plus"></span>
          Mi Carrito
      </a>
            
    {% else %}
            <a class="nav-item nav-link {% if request.path == login %}active{% endif %}"" href="{{ login }}">
            <span class="fas fa-user"></span>
            Login
        </a>
        <a class="nav-item nav-link {% if request.path == register %}active{% endif %}" href="{{ register }}">
            <span class="fas fa-user-plus"></span>
            Registro

        
        </a>


    {% endif %}

      </div>
    </div>
  </nav>