Django-Tienda-Virtual--master/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

Django-Tienda-Virtual--master/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order')
]

Django-Tienda-Virtual--master/products/urls.py
from django.urls import path

from . import views

#con esto decimos que todas estas rutas son de la aplicacion products y asi nos evitamos en conflicto
#entre rutas, podemos tener dos o mas rutas con el mismo nombre
app_name = 'products'


urlpatterns = [
    path('search',views.ProductSearchListView.as_view() , name="search"),
    path('<slug:slug>',views.ProductDetailView.as_view() , name="product"),

]

Django-Tienda-Virtual--master/tiendovirtual/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path('usuarios/login', views.login_view, name="login"),
    path('usuarios/logout', views.logout_view, name="logout"),
    path('usuarios/registro', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
      path('orden/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-Tienda-Virtual--master/carts/models.py
import uuid
import decimal
from django.db import models
from users.models import User
from products.models import Product
from django.db.models.signals import pre_save,post_save
from django.db.models.signals import m2m_changed
# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05 #comision del 5% de la compra

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        #este es el propety que se definió
        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        #products_related() permite obtener los objetos products y cartproducts en una misma consulta
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
        ])
        self.save() #actualzizamos en la base de datos
    
    def update_total(self):
        self.total = self.subtotal*decimal.Decimal(1+Cart.FEE)
        self.save() 

    def products_related(self):
        #estamos obteniendo todos los objetos cartproducts y product en una sola consulta
        return self.cartproducts_set.select_related('product')

    @property
    def order(self):
        return self.order_set.first()



class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity
        object.update_quantity(quantity)
        return object
class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    #si el carrito no posee un identificador unico
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    #cuando un producto se agrege, se elimine o el carrito se limpie
    #se calcula el subtotal y total del carrito
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

#callbacks
pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

Django-Tienda-Virtual--master/carts/views.py
from django.shortcuts import render
from products.models import Product
from django.shortcuts import redirect, get_object_or_404
from .models import Cart 
from .utils import get_or_create_cart
from .models import CartProducts

# Create your views here.

def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {
        #mandando el objeto cart al template
        'cart':cart
    })

def add(request):
    #estos nombres son los nombres del formulario los que obtiene el request
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    # si esa llave no existe, el valor de la llave será uno por default de productos
    quantity = int(request.POST.get('quantity', 1))


    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, product=product, quantity=quantity)
    #esta forma de agregar no esta BIEN PORQUE CADA VEZ QUE AGREGO NUEVOS NO SE ACTUALIZA, SOLO LOS QUE ENVIE EN EL MOMENTO
    #cart.products.add(product, through_defaults={
    #    'quantity': quantity
    #    
    #})
    #'product_id' es el nombre del formulario html donde obtiene el id del producto
    product = Product.objects.get(pk=request.POST.get('product_id'))
    #cart es una instacia del modelo por lo que para acceder a atributo products es la relacion ManytoMany
    cart.products.add(product)

    return render(request, 'carts/add.html', {
        'quantity': quantity,
        'product': product,
        'cp': cart_product
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    #'product_id' es el nombre del formulario html donde obtiene el id del producto
    product = Product.objects.get(pk=request.POST.get('product_id'))
    #cart es una instacia del modelo por lo que para acceder a atributo products es la relacion ManytoMany
    cart.products.remove(product)

    return redirect('carts:cart')

Django-Tienda-Virtual--master/carts/templates/carts/add.html
{% extends 'base.html' %}
{% load static %}
{% load product_extras %}



{% block content %}

<div class="col-3">
{% if product.image %}
    <img src="{{product.image.url}}" alt="Imagen del producto" with="200" height="200">

{% endif %}
</div>

<div class="col mt-2">
    <div class="h3 font-weight-bold text-success">
    
    {{quantity | quantity_add_format }} al carrito
    </div>
    <div class="h5">
        <a href="{% url 'products:product' product.slug %}">
        {{product.title}}
    </a>
    <div class=" h5 font-weight-bold text-danger">
        {{product.price | price_format }}

    </div>
    <div class="mt-2">
    <a href="{% url 'carts:cart' %}" class="btn btn-warning">Ver Carrito</a>
    </div>
        <div class="mt-2">
     <a href="{% url 'index' %}" class="btn btn-success">Seguir comprando</a>
    </div>

</div>

{% endblock  %}

Django-Tienda-Virtual--master/carts/templates/carts/cart.html
 {% extends 'base.html' %}
{% load product_extras %}

{% block  content %}

{% if cart.products.exists %}
<div class="col-8">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th  scope="row">🛍️ Producto</th>
                    <th  scope="row">🧮 Cantidad</th>
                    <th  scope="row">💲 Precio</th>
                </tr>
            </thead>
            <tbody>

                {% for cp in cart.products_related %}
                    {% with product=cp.product %}
                <tr>
                    <th>{{ forloop.couter }}</th>
                    <th> 

                        {% if product.image %}
                        <img src="{{ product.image.url}}" alt="Imagen del Producto" width="60" height="60">
                        {% endif%}
                    </th>
                    <th>
                        <a href="{% url 'products:product' product.slug %}">
                            {{ product.title}}
                        </a>
                        {% include 'carts/snippets/remove.html'%}
                    </th>
                    <th>
                        {{ cp.quantity}}
                    </th>
                    <th>
                        <span class="font-weight-bold text-danger">{{product.price | price_format}}</span>
                    </th>
                </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
</div>

<div class="col mt-4">
  <div class="card mt-4">
    <div class="card-body">
    <div class="font-weight-bold">
        Subtotal: ({{ cart.products.count}}) <span class="text-danger">{{ cart.subtotal | price_format }}</span>
    </div>
    <div class="mt-2">
        <a href="{% url 'orders:order' %}" class="btn btn-success">💳 Proceder al pago</a>
    </div>
    </div>
   </div>
</div>


{% else %}
<div class="col">
    <p class="h3">Tu carrito de compras está vacío.</p>
    <a href="{% url 'index' %}">Seguir comprando</a>

</div>
{% endif %}

{% endblock  %}